// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types'
import type * as prismicClient from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type FirstLevelPageDocumentDataSlicesSlice =
	| SyntaxHighlighterSlice
	| ArticlesGridSlice
	| HeroBannerSlice
	| AccordionSlice
	| CardsGridSlice
	| ContactsSlice
	| RichTextSlice
	| ImageAndTextSlice
	| StatisticsSlice
	| PartnersSlice
	| CallToActionSlice
	| TimelineSlice

/**
 * Content for Pagina di primo livello documents
 */
interface FirstLevelPageDocumentData {
	/**
	 * Titolo field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_level_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Mostra breadcrumb field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: first_level_page.show_breadcrumb
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	show_breadcrumb: prismic.BooleanField

	/**
	 * Slice Zone field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_level_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FirstLevelPageDocumentDataSlicesSlice> /**
	 * No index field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: first_level_page.no_index
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	no_index: prismic.BooleanField

	/**
	 * SEO title field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_level_page.seo_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_title: prismic.KeyTextField

	/**
	 * SEO description field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_level_page.seo_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_description: prismic.KeyTextField

	/**
	 * OG image field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: first_level_page.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>

	/**
	 * Schema.org type field in *Pagina di primo livello*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: WebPage
	 * - **API ID Path**: first_level_page.schema_org_type
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	schema_org_type: prismic.SelectField<
		'WebPage' | 'AboutPage' | 'Article' | 'Blog' | 'BlogPosting' | 'ContactPage' | 'NewsArticle' | 'Service',
		'filled'
	>
}

/**
 * Pagina di primo livello document from Prismic
 *
 * - **API ID**: `first_level_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FirstLevelPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<FirstLevelPageDocumentData>,
	'first_level_page',
	Lang
>

/**
 * Item in *Footer → Link con icone*
 */
export interface FooterDocumentDataIconLinksItem {
	/**
	 * Icona field in *Footer → Link con icone*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.icon_links[].icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	icon: prismic.KeyTextField

	/**
	 * Link field in *Footer → Link con icone*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.icon_links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField

	/**
	 * Alt text field in *Footer → Link con icone*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.icon_links[].alt_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	alt_text: prismic.KeyTextField
}

/**
 * Item in *Footer → Link testuali*
 */
export interface FooterDocumentDataTextLinksItem {
	/**
	 * Testo field in *Footer → Link testuali*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.text_links[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField

	/**
	 * Link field in *Footer → Link testuali*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.text_links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField

	/**
	 * Nome accessibile field in *Footer → Link testuali*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.text_links[].accessible_name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	accessible_name: prismic.KeyTextField
}

type FooterDocumentDataSlicesSlice = never

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Logo field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Dati del sito field in *Footer*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.site_data
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	site_data: prismic.RichTextField

	/**
	 * Dati societari field in *Footer*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.company_data
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	company_data: prismic.RichTextField

	/**
	 * Link con icone field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.icon_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	icon_links: prismic.GroupField<Simplify<FooterDocumentDataIconLinksItem>>

	/**
	 * Link testuali field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.text_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	text_links: prismic.GroupField<Simplify<FooterDocumentDataTextLinksItem>>

	/**
	 * Slice Zone field in *Footer*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Logo field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Label scelta linguaggio field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.language_choose_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	language_choose_label: prismic.KeyTextField

	/**
	 * Label apertura sidebar field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.open_sidebar_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	open_sidebar_label: prismic.KeyTextField

	/**
	 * Label chiusura sidebar field in *Header*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.close_sidebar_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	close_sidebar_label: prismic.KeyTextField
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>

type HomepageDocumentDataSlicesSlice =
	| SyntaxHighlighterSlice
	| TimelineSlice
	| ArticlesGridSlice
	| HeroBannerSlice
	| ImageAndTextSlice
	| RichTextSlice
	| CardsGridSlice
	| AccordionSlice
	| ContactsSlice
	| StatisticsSlice
	| PartnersSlice
	| CallToActionSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Titolo field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * SEO title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seo_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_title: prismic.KeyTextField

	/**
	 * SEO description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.seo_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_description: prismic.KeyTextField

	/**
	 * OG image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>

type NavigationMenuDocumentDataSlicesSlice = NavigationMenuSlice

/**
 * Content for Navigation menu documents
 */
interface NavigationMenuDocumentData {
	/**
	 * Aria label field in *Navigation menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.aria_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	aria_label: prismic.KeyTextField

	/**
	 * Slice Zone field in *Navigation menu*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<NavigationMenuDocumentDataSlicesSlice>
}

/**
 * Navigation menu document from Prismic
 *
 * - **API ID**: `navigation_menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavigationMenuDocumentData>,
	'navigation_menu',
	Lang
>

type SecondLevelPageDocumentDataSlicesSlice =
	| SyntaxHighlighterSlice
	| ArticlesGridSlice
	| HeroBannerSlice
	| CardsGridSlice
	| AccordionSlice
	| ContactsSlice
	| RichTextSlice
	| ImageAndTextSlice
	| StatisticsSlice
	| PartnersSlice
	| CallToActionSlice
	| TimelineSlice

/**
 * Content for Pagina di secondo livello documents
 */
interface SecondLevelPageDocumentData {
	/**
	 * È un articolo field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: second_level_page.is_article
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	is_article: prismic.BooleanField

	/**
	 * Titolo field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sezione field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.section
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	section: prismic.ContentRelationshipField<'first_level_page'>

	/**
	 * Immagine di anteprima field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.preview_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	preview_image: prismic.ImageField<never>

	/**
	 * Mostra breadcrumb field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: second_level_page.show_breadcrumb
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	show_breadcrumb: prismic.BooleanField

	/**
	 * Label data di pubblicazione field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.publication_date_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	publication_date_label: prismic.KeyTextField

	/**
	 * Data di pubblicazione field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.publication_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	publication_date: prismic.KeyTextField

	/**
	 * Data di pubblicazione per sort field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.publication_date_sort
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	publication_date_sort: prismic.DateField

	/**
	 * Label ultima revisione field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.latest_revision_date_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	latest_revision_date_label: prismic.KeyTextField

	/**
	 * Ultima revisione field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.latest_revision_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	latest_revision_date: prismic.KeyTextField

	/**
	 * Ultima revisione per sort field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.latest_revision_date_sort
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	latest_revision_date_sort: prismic.DateField

	/**
	 * Slice Zone field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SecondLevelPageDocumentDataSlicesSlice> /**
	 * No index field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: second_level_page.no_index
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	no_index: prismic.BooleanField

	/**
	 * SEO title field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.seo_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_title: prismic.KeyTextField

	/**
	 * SEO description field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.seo_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	seo_description: prismic.KeyTextField

	/**
	 * OG image field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: second_level_page.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>

	/**
	 * Schema.org type field in *Pagina di secondo livello*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: WebPage
	 * - **API ID Path**: second_level_page.schema_org_type
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	schema_org_type: prismic.SelectField<
		'WebPage' | 'AboutPage' | 'Article' | 'Blog' | 'BlogPosting' | 'ContactPage' | 'NewsArticle' | 'Service',
		'filled'
	>
}

/**
 * Pagina di secondo livello document from Prismic
 *
 * - **API ID**: `second_level_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecondLevelPageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SecondLevelPageDocumentData>,
	'second_level_page',
	Lang
>

export type AllDocumentTypes =
	| FirstLevelPageDocument
	| FooterDocument
	| HeaderDocument
	| HomepageDocument
	| NavigationMenuDocument
	| SecondLevelPageDocument

/**
 * Primary content in *Accordion → Default → Primary*
 */
export interface AccordionSliceDefaultPrimary {
	/**
	 * Titolo field in *Accordion → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *Accordion → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Margine superiore field in *Accordion → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: accordion.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *Accordion → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: accordion.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *Accordion → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: accordion.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Primary content in *Accordion → Items*
 */
export interface AccordionSliceDefaultItem {
	/**
	 * Titolo field in *Accordion → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Descrizione field in *Accordion → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordion.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AccordionSliceDefaultPrimary>,
	Simplify<AccordionSliceDefaultItem>
>

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<'accordion', AccordionSliceVariation>

/**
 * Primary content in *ArticlesGrid → Selected articles → Primary*
 */
export interface ArticlesGridSliceDefaultPrimary {
	/**
	 * Titolo field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Margine superiore field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Centra contenuto card field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.default.primary.center_card_content
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	center_card_content: prismic.BooleanField

	/**
	 * CTA blog link field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.blog_cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	blog_cta_link: prismic.LinkField

	/**
	 * CTA blog label field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.blog_cta_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blog_cta_label: prismic.KeyTextField

	/**
	 * CTA blog label accessibile field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.blog_cta_accessible_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	blog_cta_accessible_label: prismic.KeyTextField

	/**
	 * CTA accessibile articolo field in *ArticlesGrid → Selected articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.default.primary.cta_accessible_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_accessible_label: prismic.KeyTextField
}

/**
 * Primary content in *ArticlesGrid → Items*
 */
export interface ArticlesGridSliceDefaultItem {
	/**
	 * Articolo field in *ArticlesGrid → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.items[].article
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	article: prismic.ContentRelationshipField
}

/**
 * Selected articles variation for ArticlesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ArticlesGridSliceDefaultPrimary>,
	Simplify<ArticlesGridSliceDefaultItem>
>

/**
 * Primary content in *ArticlesGrid → All articles → Primary*
 */
export interface ArticlesGridSliceAllArticlesPrimary {
	/**
	 * Titolo field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.allArticles.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.allArticles.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Margine superiore field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.allArticles.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.allArticles.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.allArticles.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Centra contenuto card field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: articles_grid.allArticles.primary.center_card_content
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	center_card_content: prismic.BooleanField

	/**
	 * CTA testo accessibile field in *ArticlesGrid → All articles → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: articles_grid.allArticles.primary.cta_accessible_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_accessible_text: prismic.KeyTextField
}

/**
 * All articles variation for ArticlesGrid Slice
 *
 * - **API ID**: `allArticles`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesGridSliceAllArticles = prismic.SharedSliceVariation<
	'allArticles',
	Simplify<ArticlesGridSliceAllArticlesPrimary>,
	never
>

/**
 * Slice variation for *ArticlesGrid*
 */
type ArticlesGridSliceVariation = ArticlesGridSliceDefault | ArticlesGridSliceAllArticles

/**
 * ArticlesGrid Shared Slice
 *
 * - **API ID**: `articles_grid`
 * - **Description**: ArticlesGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesGridSlice = prismic.SharedSlice<'articles_grid', ArticlesGridSliceVariation>

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
	/**
	 * Label field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField

	/**
	 * Label accessibile field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.accessible_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	accessible_label: prismic.KeyTextField

	/**
	 * Link field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField

	/**
	 * Dimensione field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: call_to_action.default.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	size: prismic.BooleanField

	/**
	 * Margine superiore field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: call_to_action.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: call_to_action.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: call_to_action.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CallToActionSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<'call_to_action', CallToActionSliceVariation>

/**
 * Primary content in *CardsGrid → Default → Primary*
 */
export interface CardsGridSliceDefaultPrimary {
	/**
	 * Titolo field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Margine superiore field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards_grid.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards_grid.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards_grid.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Centra contenuto card field in *CardsGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards_grid.default.primary.center_card_content
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	center_card_content: prismic.BooleanField
}

/**
 * Primary content in *CardsGrid → Items*
 */
export interface CardsGridSliceDefaultItem {
	/**
	 * Icona card field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].card_icon
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	card_icon: prismic.KeyTextField

	/**
	 * Titolo card field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].card_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	card_title: prismic.KeyTextField

	/**
	 * Descrizione card field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].card_desc
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	card_desc: prismic.RichTextField

	/**
	 * CTA Link field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField

	/**
	 * CTA Testo accessibile field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].cta_accessible_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_accessible_text: prismic.KeyTextField

	/**
	 * Sfondo field in *CardsGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards_grid.items[].background
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background: prismic.ImageField<never>
}

/**
 * Default variation for CardsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: CardsGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardsGridSliceDefaultPrimary>,
	Simplify<CardsGridSliceDefaultItem>
>

/**
 * Slice variation for *CardsGrid*
 */
type CardsGridSliceVariation = CardsGridSliceDefault

/**
 * CardsGrid Shared Slice
 *
 * - **API ID**: `cards_grid`
 * - **Description**: CardsGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsGridSlice = prismic.SharedSlice<'cards_grid', CardsGridSliceVariation>

/**
 * Primary content in *Contacts → Default → Primary*
 */
export interface ContactsSliceDefaultPrimary {
	/**
	 * Background 1 field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.background_1
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_1: prismic.ImageField<never>

	/**
	 * Background 2 field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.background_2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_2: prismic.ImageField<never>

	/**
	 * Titolo field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Testo field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField

	/**
	 * Link bottone field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField

	/**
	 * Label bottone field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.default.primary.button_label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_label: prismic.KeyTextField

	/**
	 * Margine superiore field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: contacts.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: contacts.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: contacts.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Abilita background field in *Contacts → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: contacts.default.primary.enable_bg
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_bg: prismic.BooleanField
}

/**
 * Primary content in *Contacts → Items*
 */
export interface ContactsSliceDefaultItem {
	/**
	 * Face field in *Contacts → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contacts.items[].face
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	face: prismic.ImageField<never>
}

/**
 * Default variation for Contacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Contacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactsSliceDefaultPrimary>,
	Simplify<ContactsSliceDefaultItem>
>

/**
 * Slice variation for *Contacts*
 */
type ContactsSliceVariation = ContactsSliceDefault

/**
 * Contacts Shared Slice
 *
 * - **API ID**: `contacts`
 * - **Description**: Contacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactsSlice = prismic.SharedSlice<'contacts', ContactsSliceVariation>

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
	/**
	 * Titolo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField

	/**
	 * Margine inferiore titolo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_banner.default.primary.title_mb
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	title_mb: prismic.BooleanField

	/**
	 * Sottotitolo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField

	/**
	 * Immagine di sfondo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>

	/**
	 * Blur immagine di sfondo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_banner.default.primary.background_image_blur
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	background_image_blur: prismic.BooleanField

	/**
	 * Margine superiore field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_banner.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_banner.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * CTA link field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField

	/**
	 * CTA testo field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_banner.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text: prismic.KeyTextField

	/**
	 * Abilita animazione field in *HeroBanner → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_banner.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroBannerSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<'hero_banner', HeroBannerSliceVariation>

/**
 * Primary content in *ImageAndText → Default → Primary*
 */
export interface ImageAndTextSliceDefaultPrimary {
	/**
	 * Immagine field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>

	/**
	 * Titolo field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Descrizione field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField

	/**
	 * Margine superiore field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_and_text.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_and_text.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Layout specchiato field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_and_text.default.primary.reverse
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	reverse: prismic.BooleanField

	/**
	 * CTA Link field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField

	/**
	 * CTA Testo field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text: prismic.KeyTextField

	/**
	 * CTA Testo accessible field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_and_text.default.primary.cta_accessible_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_accessible_text: prismic.KeyTextField

	/**
	 * Abilita animazione field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_and_text.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Abilita sfondo field in *ImageAndText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: image_and_text.default.primary.enable_bg
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_bg: prismic.BooleanField
}

/**
 * Default variation for ImageAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ImageAndTextSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *ImageAndText*
 */
type ImageAndTextSliceVariation = ImageAndTextSliceDefault

/**
 * ImageAndText Shared Slice
 *
 * - **API ID**: `image_and_text`
 * - **Description**: ImageAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSlice = prismic.SharedSlice<'image_and_text', ImageAndTextSliceVariation>

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationMenuSliceDefaultPrimary {
	/**
	 * URL link field in *NavigationItem → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.default.primary.link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_url: prismic.LinkField

	/**
	 * Titolo link field in *NavigationItem → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.default.primary.link_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_title: prismic.KeyTextField

	/**
	 * Nascondi su desktop field in *NavigationItem → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: navigation_menu.default.primary.hide_on_desktop
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	hide_on_desktop: prismic.BooleanField
}

/**
 * Primary content in *NavigationItem → Items*
 */
export interface NavigationMenuSliceDefaultItem {
	/**
	 * URL link field in *NavigationItem → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.items[].link_url
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link_url: prismic.LinkField

	/**
	 * Titolo link field in *NavigationItem → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: navigation_menu.items[].link_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link_title: prismic.KeyTextField
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NavigationMenuSliceDefaultPrimary>,
	Simplify<NavigationMenuSliceDefaultItem>
>

/**
 * Slice variation for *NavigationItem*
 */
type NavigationMenuSliceVariation = NavigationMenuSliceDefault

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_menu`
 * - **Description**: NavigationMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationMenuSlice = prismic.SharedSlice<'navigation_menu', NavigationMenuSliceVariation>

/**
 * Primary content in *Partners → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
	/**
	 * Titolo field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Margine superiore field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Padding superiore field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.padding_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	padding_top: prismic.BooleanField

	/**
	 * Padding inferiore field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.padding_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	padding_bottom: prismic.BooleanField

	/**
	 * Abilita sfondo field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: partners.default.primary.enable_bg
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_bg: prismic.BooleanField

	/**
	 * Titolo sezione field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.default.primary.section_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_title: prismic.KeyTextField

	/**
	 * Sottotitolo sezione field in *Partners → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.default.primary.section_subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	section_subtitle: prismic.KeyTextField
}

/**
 * Primary content in *Partners → Items*
 */
export interface PartnersSliceDefaultItem {
	/**
	 * Logo field in *Partners → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.items[].logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Nome field in *Partners → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField

	/**
	 * Link field in *Partners → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partners.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PartnersSliceDefaultPrimary>,
	Simplify<PartnersSliceDefaultItem>
>

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<'partners', PartnersSliceVariation>

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Testo field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField

	/**
	 * Allineamento field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.text_align
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	text_align: prismic.SelectField<'Left' | 'Center' | 'Right'>

	/**
	 * Margine superiore field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: rich_text.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: rich_text.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: rich_text.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField

	/**
	 * Dimensione testo field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Scegliere una dimensione del testo
	 * - **Default Value**: Default
	 * - **API ID Path**: rich_text.default.primary.text_size
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	text_size: prismic.SelectField<'Default' | 'Grande' | 'Piccola', 'filled'>
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<'default', Simplify<RichTextSliceDefaultPrimary>, never>

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
	/**
	 * Margine superiore field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: statistics.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: statistics.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Titolo field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subtitle: prismic.RichTextField

	/**
	 * Abilita animazione field in *Statistics → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: statistics.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Primary content in *Statistics → Items*
 */
export interface StatisticsSliceDefaultItem {
	/**
	 * Data field in *Statistics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.items[].data
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	data: prismic.KeyTextField

	/**
	 * Description field in *Statistics → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: statistics.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<StatisticsSliceDefaultPrimary>,
	Simplify<StatisticsSliceDefaultItem>
>

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatisticsSlice = prismic.SharedSlice<'statistics', StatisticsSliceVariation>

/**
 * Primary content in *SyntaxHighlighter → Default → Primary*
 */
export interface SyntaxHighlighterSliceDefaultPrimary {
	/**
	 * Linguaggio field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: Seleziona il linguaggio da renderizzare
	 * - **Default Value**: javascript
	 * - **API ID Path**: syntax_highlighter.default.primary.language
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	language: prismic.SelectField<'javascript' | 'typescript', 'filled'>

	/**
	 * Codice field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Incolla qua lo snippet di codice
	 * - **API ID Path**: syntax_highlighter.default.primary.code
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	code: prismic.KeyTextField

	/**
	 * Altezza massima field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: In pixel
	 * - **API ID Path**: syntax_highlighter.default.primary.max_height
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	max_height: prismic.NumberField

	/**
	 * Margine superiore field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: syntax_highlighter.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: syntax_highlighter.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *SyntaxHighlighter → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: syntax_highlighter.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Default variation for SyntaxHighlighter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SyntaxHighlighterSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SyntaxHighlighterSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *SyntaxHighlighter*
 */
type SyntaxHighlighterSliceVariation = SyntaxHighlighterSliceDefault

/**
 * SyntaxHighlighter Shared Slice
 *
 * - **API ID**: `syntax_highlighter`
 * - **Description**: SyntaxHighlighter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SyntaxHighlighterSlice = prismic.SharedSlice<'syntax_highlighter', SyntaxHighlighterSliceVariation>

/**
 * Primary content in *Timeline → Default → Primary*
 */
export interface TimelineSliceDefaultPrimary {
	/**
	 * Titolo field in *Timeline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: timeline.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Sottotitolo field in *Timeline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: timeline.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField

	/**
	 * Margine superiore field in *Timeline → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: timeline.default.primary.margin_top
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_top: prismic.BooleanField

	/**
	 * Margine inferiore field in *Timeline → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: timeline.default.primary.margin_bottom
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	margin_bottom: prismic.BooleanField

	/**
	 * Abilita animazione field in *Timeline → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: timeline.default.primary.enable_animation
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	enable_animation: prismic.BooleanField
}

/**
 * Primary content in *Timeline → Items*
 */
export interface TimelineSliceDefaultItem {
	/**
	 * Numero field in *Timeline → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: timeline.items[].number
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	number: prismic.KeyTextField

	/**
	 * Titolo field in *Timeline → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: timeline.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField

	/**
	 * Contenuto field in *Timeline → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: timeline.items[].content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField
}

/**
 * Default variation for Timeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TimelineSliceDefaultPrimary>,
	Simplify<TimelineSliceDefaultItem>
>

/**
 * Slice variation for *Timeline*
 */
type TimelineSliceVariation = TimelineSliceDefault

/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline`
 * - **Description**: Timeline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TimelineSlice = prismic.SharedSlice<'timeline', TimelineSliceVariation>

declare module '@prismicio/client' {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismicClient.WriteClientConfig
		): prismicClient.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismicClient.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			FirstLevelPageDocument,
			FirstLevelPageDocumentData,
			FirstLevelPageDocumentDataSlicesSlice,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataIconLinksItem,
			FooterDocumentDataTextLinksItem,
			FooterDocumentDataSlicesSlice,
			HeaderDocument,
			HeaderDocumentData,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			NavigationMenuDocument,
			NavigationMenuDocumentData,
			NavigationMenuDocumentDataSlicesSlice,
			SecondLevelPageDocument,
			SecondLevelPageDocumentData,
			SecondLevelPageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AccordionSlice,
			AccordionSliceDefaultPrimary,
			AccordionSliceDefaultItem,
			AccordionSliceVariation,
			AccordionSliceDefault,
			ArticlesGridSlice,
			ArticlesGridSliceDefaultPrimary,
			ArticlesGridSliceDefaultItem,
			ArticlesGridSliceAllArticlesPrimary,
			ArticlesGridSliceVariation,
			ArticlesGridSliceDefault,
			ArticlesGridSliceAllArticles,
			CallToActionSlice,
			CallToActionSliceDefaultPrimary,
			CallToActionSliceVariation,
			CallToActionSliceDefault,
			CardsGridSlice,
			CardsGridSliceDefaultPrimary,
			CardsGridSliceDefaultItem,
			CardsGridSliceVariation,
			CardsGridSliceDefault,
			ContactsSlice,
			ContactsSliceDefaultPrimary,
			ContactsSliceDefaultItem,
			ContactsSliceVariation,
			ContactsSliceDefault,
			HeroBannerSlice,
			HeroBannerSliceDefaultPrimary,
			HeroBannerSliceVariation,
			HeroBannerSliceDefault,
			ImageAndTextSlice,
			ImageAndTextSliceDefaultPrimary,
			ImageAndTextSliceVariation,
			ImageAndTextSliceDefault,
			NavigationMenuSlice,
			NavigationMenuSliceDefaultPrimary,
			NavigationMenuSliceDefaultItem,
			NavigationMenuSliceVariation,
			NavigationMenuSliceDefault,
			PartnersSlice,
			PartnersSliceDefaultPrimary,
			PartnersSliceDefaultItem,
			PartnersSliceVariation,
			PartnersSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			StatisticsSlice,
			StatisticsSliceDefaultPrimary,
			StatisticsSliceDefaultItem,
			StatisticsSliceVariation,
			StatisticsSliceDefault,
			SyntaxHighlighterSlice,
			SyntaxHighlighterSliceDefaultPrimary,
			SyntaxHighlighterSliceVariation,
			SyntaxHighlighterSliceDefault,
			TimelineSlice,
			TimelineSliceDefaultPrimary,
			TimelineSliceDefaultItem,
			TimelineSliceVariation,
			TimelineSliceDefault
		}
	}
}
