// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import CardsGrid from './CardsGrid';
import Contacts from './Contacts';
import HeroBanner from './HeroBanner';
import ImageAndText from './ImageAndText';
import Partners from './Partners';
import RichText from './RichText';
import Statistics from './Statistics';

export {
	Accordion,
	CardsGrid,
	Contacts,
	HeroBanner,
	ImageAndText,
	Partners,
	RichText,
	Statistics,
};

export const components = {
	accordion: Accordion,
	cards_grid: CardsGrid,
	contacts: Contacts,
	hero_banner: HeroBanner,
	image_and_text: ImageAndText,
	partners: Partners,
	rich_text: RichText,
	statistics: Statistics,
};
