// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
	accordion: () => import(/* webpackChunkName: "prismic__slices__accordion" */ './Accordion/index.vue'),
	articles_grid: () => import(/* webpackChunkName: "prismic__slices__articles_grid" */ './ArticlesGrid/index.vue'),
	call_to_action: () => import(/* webpackChunkName: "prismic__slices__call_to_action" */ './CallToAction/index.vue'),
	cards_grid: () => import(/* webpackChunkName: "prismic__slices__cards_grid" */ './CardsGrid/index.vue'),
	contacts: () => import(/* webpackChunkName: "prismic__slices__contacts" */ './Contacts/index.vue'),
	hero_banner: () => import(/* webpackChunkName: "prismic__slices__hero_banner" */ './HeroBanner/index.vue'),
	image_and_text: () => import(/* webpackChunkName: "prismic__slices__image_and_text" */ './ImageAndText/index.vue'),
	navigation_menu: () =>
		import(/* webpackChunkName: "prismic__slices__navigation_menu" */ './NavigationItem/index.vue'),
	partners: () => import(/* webpackChunkName: "prismic__slices__partners" */ './Partners/index.vue'),
	rich_text: () => import(/* webpackChunkName: "prismic__slices__rich_text" */ './RichText/index.vue'),
	social_share: () => import(/* webpackChunkName: "prismic__slices__social_share" */ './SocialShare/index.vue'),
	statistics: () => import(/* webpackChunkName: "prismic__slices__statistics" */ './Statistics/index.vue'),
	syntax_highlighter: () =>
		import(/* webpackChunkName: "prismic__slices__syntax_highlighter" */ './SyntaxHighlighter/index.vue'),
	timeline: () => import(/* webpackChunkName: "prismic__slices__timeline" */ './Timeline/index.vue')
}
