// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from './Accordion';
import CardsGrid from './CardsGrid';
import Contacts from './Contacts';
import HeroBanner from './HeroBanner';
import ImageAndText from './ImageAndText';
import RichText from './RichText';

export {
	Accordion,
	CardsGrid,
	Contacts,
	HeroBanner,
	ImageAndText,
	RichText,
};

export const components = {
	accordion: Accordion,
	cards_grid: CardsGrid,
	contacts: Contacts,
	hero_banner: HeroBanner,
	image_and_text: ImageAndText,
	rich_text: RichText,
};
